services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BASE_PATH: /tools/
    container_name: myapp
    ports:
      - "3000:3000"
    restart: unless-stopped
