server {
  listen 3000;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /tools {
    return 301 /tools/;
  }

  location /tools/ {
    try_files $uri $uri/ /tools/index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
